### ISSUE TITLE
getPosition() failing

### ISSUE THREAD

**Issue by sipher256** [pixtron/bybit-api#5]
https://github.com/pixtron/bybit-api/blob/master/lib/rest-client.js#L112

Seems this is failing in the new versions because the v2 endpoint requires a "symbol" parameter (and returns different syntax)?
https://github.com/bybit-exchange/bybit-official-api-docs/blob/master/en/rest_api.md#-my-position-v2

Can you add the V1 back, or keep both in place?

**Comment by pixtron** [comment]
Sorry my bad. I re added the v1 method as `getPositions` note the `s` at the end. Although I marked the method as deprecated, as the bybit docs recommend to use the v2 method.

If the v1 method will be removed that will haben in a major release, but as long it is still present in the docs i will keep it.

Please also note the following "maybe breaking" changes in v1.1.0:

* `placeActiveOrder` uses the new v2 endpoint
* `cancelActiveOrder` uses the new v2 endpoint
* `getOrderTradeRecords` has been renamed to `getTradeRecords`

**Comment by sipher256** [comment]
No worries & thanks for the quick fix! Bit annoying from bybit to make a "v2" method that works completely differently to the v1. I spoke to them in telegram, seems the only way to get all balances once the v1 method is dropped, is 4 API calls to the new one...

Either way, appreciate the quick fix - getPositions keeps me going.
