### ISSUE TITLE
REST API Error: "invalid request,please check your server timestamp or recv_window param"

### ISSUE THREAD

**Issue by tiagosiebler** [pixtron/bybit-api#6]
Similar-ish to #1. Sometimes, rarely, I'm seeing rejections when trying to place limit orders with your module:
`invalid request,please check your server timestamp or recv_window param` is the error message.

I've sync'd my server time. It doesn't happen often, but it happens often enough to pose a risk.

I saw there's some sync logic in the request component of this module:
https://github.com/pixtron/bybit-api/blob/master/lib/request.js#L23

Would it help to reduce the sync time interval? Or do you have any ideas on how to reduce this from being an issue?

**Comment by tiagosiebler** [comment]
The bybit docs mention the optional `recv_window` param, would it help to use an increased value here? 
https://github.com/bybit-exchange/bybit-official-api-docs/blob/master/en/rest_api_sign.md#public-parameters

**Comment by tiagosiebler** [comment]
I guess it would go here?
https://github.com/pixtron/bybit-api/blob/master/lib/request.js#L91

What about setting the default here but allowing it to be overridden by an "options" object in the constructor?

**Comment by pixtron** [comment]
Closing this issue. The error can still occur when `requestTimestamp < (serverTimestamp + 1000)` as the recv_window is checked like this:

```
if (timestamp < (server_time + 1000) && (server_time - timestamp) <= recv_window) {
  // process request
} else {
  // invalid request
}
```

see: https://github.com/bybit-exchange/bybit-official-api-docs/blob/master/en/rest_api_sign.md#errors
